site_name: Reusable Components for Jetpack Compose
site_description: 'A collection of reusable components for Jetpack Compose'
site_author: 'Mohsen'
site_url: 'https://github.com/LinX64/Reusable'
edit_uri: 'tree/main/docs/'
remote_branch: gh-pages

# Repository
repo_name: 'Reusable Components for Jetpack Compose'
repo_url: https://github.com/LinX64/Reusable

theme:
  name: material
  palette:
    primary: white
    accent: red
  icon:
    repo: fontawesome/brands/github
  font:
    text: 'Roboto'
    code: 'JetBrains Mono'
  features:
    - content.action.edit
    - content.code.copy
    - content.tabs.link

plugins:
  - search

markdown_extensions:
  # Admonitions
  - admonition
  - pymdownx.details

  # Code highlight
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  # Tabs
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

  - toc:
      permalink: true

  # For images
  - attr_list
  - md_in_html

# Navigation
nav:
  - 'Overview': index.md
  - 'How to use?':
    - 'Gradle Plugin': use/using-gradle-plugin.md
    - 'CLI': use/using-cli.md
    - 'Library': use/using-utility-as-library.md